FROM node:12.18-alpine

LABEL version="1.0"

LABEL discription="Development image for music api"

WORKDIR /app

COPY ["package.json*","package-lock.json*","npm-shrinkwrap.json*", "./"]

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 5000

CMD ["npm","run","dev"]